spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javadb?useSSL=false
    username: root
    password: Yoonmin#5

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


  #JPA Settings
  jpa.hibernate.ddl_auto: create-drop







